general:
  baseDir: E:\Programming\python\pytorch\Unet3+_2\Unet3+\Code\main
  dataset:
    channel:
      image: 1
      label: 1
    links:
    - https://github.com/Zhao-BJ/Brain_3D_Vessel_Datasets
    - https://public.kitware.com/Wiki/TubeTK/Data
    name: Brain_MR_Angiography
    shape:
      x: 448
      y: 448
    type: image
  logDir: E:\Programming\python\pytorch\Unet3+_2\Unet3+\logs
  model: unet3+
  name: UNet3+ FOR UMR_dataset
  title: 'null'
test:
  datasetPath: E:\Programming\python\pytorch\Unet3+_2\Unet3+\Datasets\Brain_MR_Angiography\TubeTK\test
  resultBaseDir: E:\Programming\python\pytorch\Unet3+_2\Unet3+\result
train:
  datasetPath: E:\Programming\python\pytorch\Unet3+_2\Unet3+\Datasets\Brain_MR_Angiography\TubeTK\train
  flagPath: E:\Programming\python\pytorch\Unet3+_2\Unet3+\Code\main\flag.yml
  modelSavePath: E:\Programming\python\pytorch\Unet3+_2\Unet3+\TrainedModels
  params:
    index: 10029
    path: train-plan.csv
    type: csv
